site_name: ConnectAPI
site_description: A way to build your backend with components.
site_url: https://www.connectapi.ml/
theme:
  name: material
  palette:
  - scheme: default
    primary: orange
    accent: indigo
    toggle:
      icon: material/lightbulb
      name: Switch to dark mode
  - scheme: slate
    primary: orange
    accent: indigo
    toggle:
      icon: material/lightbulb-outline
      name: Switch to light mode
  features:
  - search.suggest
  - search.highlight
  - content.tabs.link
  icon:
    repo: fontawesome/brands/github-alt
  logo: img/icon-white.svg
  favicon: img/favicon.png
  language: en
repo_name: connectapi/connectapi
repo_url: https://github.com/connectapi/connectapi
edit_uri: ''
nav:
  - ConnectAPI: index.md
  - Tutorial - User Guide:
    - tutorial/index.md
  - CLI - actions:
    - actions/uninstall.md
    - actions/upgrading_version.md
  - help.md
  - release-notes.md
markdown_extensions:
- toc:
    permalink: true
- markdown.extensions.codehilite:
    guess_lang: false
- admonition
- codehilite
- extra
- pymdownx.superfences:
    custom_fences:
    - name: mermaid
      class: mermaid
      format: !!python/name:pymdownx.superfences.fence_div_format ''
- pymdownx.tabbed:
    alternate_style: true
- mdx_include

extra:
  social:
  - icon: fontawesome/brands/github-alt
    link: https://github.com/connectapi/connectapi
  - icon: fontawesome/brands/linkedin
    link: https://www.linkedin.com/in/yehoyada/
  - icon: fontawesome/brands/dev
    link: https://dev.to/hvuhsg
  - icon: fontawesome/solid/globe
    link: https://yoyocv.ml

extra_css:
  - css/termynal.css
  - css/custom.css

extra_javascript:
  - https://unpkg.com/mermaid@8.4.6/dist/mermaid.min.js
  - js/termynal.js
  - js/custom.js
