version: '3.1'

services:
  gateway:
    image: connectapi-gateway
    ports:
      - 1687:80
    environment:
      SECRET_KEY: ${SECRET_KEY}
      SUPER_USER_SECRET: ${SUPER_USER_SECRET}
      MONGO_URL: mongodb://gatewayname:{$GATEWAY_DB_PASSWORD}@5.183.9.78:27017/gateway
      REDIS_HOST: redis
      REDIS_PORT: 6379
      ENV: PRODUCTION
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - core

  dashboard:
    image: connectapi_dashboard
    depends_on:
      - gateway
    ports:
      - 9934:80
    environment:
      secret_key: ${SECRET_KEY}
      mongo_url: mongodb://dashusername:${DASHBOARD_DB_PASSWORD}@5.183.9.78:27017/Dashboard
      marketplace_url: {$MARKETPLACE_URL}
      gateway_url: http://gateway
      port: 80
    networks:
      - core

networks:
  core:
    driver: bridge